### PR TITLE
added linux css class, confirmed working on ubuntu 14.04

### PR DESCRIPTION
**Pull request by solancer**
Added  linux support for css headers for close, minimize and maximize.

Testing on ubuntu 14.04 and it works like a charm.

screenshot from 2016-01-25 06 22 00
screenshot from 2016-01-25 06 22 33

### CODE REVIEW

**Comment by leny** [comment]
Hi, thanks.

I will look forward during this week to generate an installer for Linux & put it on the website.

**Comment by solancer** [comment]
No problem. Also I have a feature request for this app, there is a service called ngrok that tunnels localhost port to the web in a secure manner. You can take a look at their website ngrok.com. Let me know if you interested and I would love to work on integrating it into your app.

**Comment by leny** [comment]
In my head, **Teseve** is _really_ a simple, local, testing webserver.

I'm really not fan to integrate ngrok into it, _but_: Teseve is open-source, and I will be really happy to see you fork it and manage your app integrating ngrok from the Teseve base (and definitely add a link to your fork on the Teseve website when you'll be ok).

**Comment by solancer** [comment]
I understand.. I will try adding ngrok into the app.

**Pull request merged**
